### ISSUE TITLE
CI should only test with Python 3.8+

### ISSUE THREAD

**Issue by dkliban** [pulp/pulp-cli-ostree#33]
Looks like we are testing with Python 3.6, but pulpcore already requires 3.8+. We should probably require the same for the CLI.

**Comment by mdellweg** [comment]
The cli can run on environments other than the system running Pulp. So I don't see this as a valid reason. OTOH we sure can have a discussion about supported versions.

**Comment by lubosmj** [comment]
Can this be discussed at the pulp-cli mini-team meeting, please?

**Comment by lubosmj** [comment]
Now, we test the CLI with python 3.7 and python 3.10:
https://github.com/pulp/pulp-cli-ostree/blob/33054e3eb6f46ab0eb0710d17827cb15537b8125/.github/workflows/main.yml#L18-L20
